config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :bookmarks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "recipes#index"
  resources :recipes
  resources :bookmarks, only: [ :destroy ]
  resources :categories do
    resources :bookmarks, only: [ :new, :create ]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, presence: true, length: { minimum: 6 }
  belongs_to :recipe
  belongs_to :category
  validates :recipe, uniqueness: { scope: :category,
    message: "You have already bookmarked that movie to that list" }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }, allow_nil: true
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, allow_blank: false
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }, allow_nil: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ destroy ]

  # GET /bookmarks/new
  def new
    @category = Category.find(params[:category_id])
    @bookmark =  Bookmark.new()
  end


  # POST /bookmarks or /bookmarks.json
  def create
    @category = Category.find(params[:category_id])
    @bookmark = @category.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to category_path(@category), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /bookmarks/1 or /bookmarks/1.json
  def destroy
    if @bookmark.destroy!
      redirect_to category_path(@bookmark.category), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    if @category.save!
      redirect_to category_path(@category), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.save ? (redirect_to recipe_path(@recipe)) : (render :new, status: :unprocessable_entity)
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/bookmarks/_bookmark.html.erb
<div id="<%= dom_id bookmark %>">
</div>

app/views/bookmarks/_form.html.erb
<%= simple_form_for([@category, @bookmark]) do |f| %>
<%= f.input :comment%>
<%= f.input :recipe_id, collection: Recipe.all%>
    <%= f.button :submit %>
<% end %>

app/views/bookmarks/edit.html.erb
<% content_for :title, "Editing bookmark" %>

<h1>Editing bookmark</h1>

<%= render "form", bookmark: @bookmark %>

<br>

<div>
  <%= link_to "Show this bookmark", @bookmark %> |
  <%= link_to "Back to bookmarks", bookmarks_path %>
</div>

app/views/bookmarks/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Bookmarks" %>

<h1>Bookmarks</h1>

<div id="bookmarks">
  <% @bookmarks.each do |bookmark| %>
    <%= render bookmark %>
    <p>
      <%= link_to "Show this bookmark", bookmark %>
    </p>
  <% end %>
</div>

<%= link_to "New bookmark", new_bookmark_path %>

app/views/bookmarks/new.html.erb
<% content_for :title, "New bookmark" %>

<h1>New bookmark</h1>

<%= render "form", category: @category, bookmark: @bookmark %>

<br>

<div>
  <%= link_to "Back to bookmarks", bookmarks_path %>
</div>

app/views/bookmarks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bookmark %>

<div>
  <%= link_to "Edit this bookmark", edit_bookmark_path(@bookmark) %> |
  <%= link_to "Back to bookmarks", bookmarks_path %>

  <%= button_to "Destroy this bookmark", @bookmark, method: :delete %>
</div>

app/views/categories/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @category.image_url%>)">
  <div class="row d-flex align-items-center justify-content-between mb-3 pr-4 mr-4">

    <div class="col-auto">
      <h1> <%=@category.name %></h1>
    </div>

    <div class="col-auto d-flex flex-column">
      <%= link_to categories_path() do %>
        <button type="button" class="btn btn-primary"> Back <i class="fa-solid fa-arrow-left-long"></i></button>
      <%end%>
      <%= link_to new_category_bookmark_path(@category) do %>
        <button type="button" class="btn btn-success"> Add a Recipe <i class="fa-solid fa-plus"></i> </button>
      <% end %>
      <%= link_to edit_category_path(@category) do %>
         <button type="button" class="btn btn-warning"> Edit Category<i class="fa-solid fa-pen-to-square"></i></button>
      <%end%>
      <%= link_to categories_path(@category), method: :delete do%>
        <button type="button" class="btn btn-danger"> Delete Category <i class="fa-solid fa-trash"></i> </button>
      <% end %>
    </div>

  </div>
</div>

app/views/categories/_category.html.erb
    <div class="col-auto">
        <div class="card border-secondary mb-3 rounded shadow-lg" style="max-width: 25rem; max-height: 20rem">
          <div class="custom-image-container d-flex align-items-center justify-content-center">
            <img class="card-img-top" src="<%= "#{category.image_url}" %>" alt="Card image cap">
          </div>
            <div class="card-body">
                <h5 class="card-title"><%= "#{category.name}"%></h5>
              <h6 class="card-subtitle mb-2 text-muted">Rating:</h6>
            </div>
        </div>
    </div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
    <%=f.input :name %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>
<%= link_to new_category_path do%>
<button  type="button" class="btn btn-primary">
  New List <i class="fa-solid fa-plus"></i>
</button>
<%end%>

<div class="container" id="categories">
<div class="row row-cols-1 row-cols-md-2 g-4">
      <% @categories.each do |category| %>
        <%= link_to category_path(category), class: "list-group-item list-group-item-action" do %>
          <%= render category%>
        <% end %>
      <%end%>
</div>
</div>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render "banner", category: @category %>

<div class="container" id="recipes">
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <% @category.bookmarks.each do |bookmark| %>
    <div class="col-auto">

        <div class="card border-secondary mb-3 rounded shadow-lg" style="max-width: 25rem; max-height: 20rem">

          <div class="custom-image-container d-flex align-items-center justify-content-center">
            <img class="card-img-top" src="<%= "#{bookmark.recipe.image_url}" %>" alt="Card image cap">
          </div>

          <div class="card-body">
            <%= link_to recipe_path(bookmark.recipe) do %>
              <h5 class="card-title"><%= "#{bookmark.recipe.name}"%></h5>
            <%end%>
            <h6 class="card-subtitle mb-2 text-muted">Rating: <%= "#{bookmark.recipe.rating}" %></h6>
            <div class="text-clamp">
              <p class="card-text"><%= "#{bookmark.recipe.description}" %></p>
            </div>
          </div>

          <div class="card-footer">
            <div class="row d-flex align-items-center justify-content-between pr-4 mr-4">
              <div class="col-auto">
                <i class="fa-solid fa-quote-left"></i><small class="text-body-secondary"><%="#{bookmark.comment}"%></small> <i class="fa-solid fa-quote-right"></i>
              </div>
              <div class="col-auto">
                <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "delete-link" do %>
                  <i class="fas fa-trash"> </i>
                <%end%>
              </div>
            </div>
          </div>
        </div>
    </div>
    <%end%>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Cookbook" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :application, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe) do |f| %>
<%= f.input :name%>
<%= f.input :description%>
<%= f.input :rating %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
    <div class="col">
        <div class="card border-secondary mb-3 rounded shadow-lg" style="max-width: 25rem; max-height: 20rem">
          <div class="custom-image-container d-flex align-items-center justify-content-center">
            <img class="card-img-top" src="<%= "#{recipe.image_url}" %>" alt="Card image cap">
          </div>
            <div class="card-body">
              <%= link_to recipe_path(recipe) do %>
                <h5 class="card-title"><%= "#{recipe.name}"%></h5>
              <%end%>
              <h6 class="card-subtitle mb-2 text-muted">Rating: <%= "#{recipe.rating}" %></h6>
              <div class="text-clamp">
                <p class="card-text"><%= "#{recipe.description}" %></p>
              </div>
            </div>
        </div>
    </div>

app/views/recipes/edit.html.erb
<% content_for :title, "Editing recipe" %>

<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Recipes" %>

<div class= "container">

  <div class="row d-flex align-items-center justify-content-between mb-3 pr-4 mr-4">
   <div class="col-auto">
      <h1 class="mb-0">Recipes </h1>
    </div>
     <div class="col-auto">
      <%= link_to new_recipe_path(@category) do %>
        <button type="button" class="btn btn-success"> Add a Recipe <i class="fa-solid fa-plus"></i> </button>
      <% end %>
    </div>
  </div>
</div>

<div class="container" id="recipes">
<div class="row row-cols-1 row-cols-md-2 g-4">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<% content_for :title, "New recipe" %>

<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <div class="navbar-brand" ><%= image_tag "recipe_icon.png", alt: "Movies", width: 65, height: 65 %></div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", recipes_path(), class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path(), class: "nav-link active" %>
        </li>
        <li class=nav-item>
        <%= link_to "New Category", new_category_path(), class: "nav-link active" %>
        </li>
        </ul>
  </div>
  </div>
</nav>